Replace most 'test' or '['...']' with '[['...']]' in indird/indird

diff --git a/indird/indird b/indird/indird
--- a/indird/indird
+++ b/indird/indird
@@ -117,7 +117,7 @@ Fold()
 
     fcmd=$(command -v 'fold')
     test "$COLUMNS" && ncol="$COLUMNS" || ncol=$(stty -a | sed -nr 's/^.* columns ([0-9]+); .*$/\1/p')
-    test "$fcmd" -a "$ncol" || { echo "$1"; return; }
+    [[ "$fcmd" && "$ncol" ]] || { echo "$1"; return; }
     $fcmd -s -w $ncol <<< "$1"
 }
 
@@ -311,7 +311,7 @@ ChkConf()
 	test -v Conf["$key"] || ConfErr "required '$key' property is missing"
     done
     # Make sure that ${Conf['path']} exists
-    test -d "${Conf['path']}" -o "$NLocal" || ConfErr "path \"${Conf['path']}\" does not exist" $ExNoPath
+    [[ -d "${Conf['path']}" || "$NLocal" ]] || ConfErr "path \"${Conf['path']}\" does not exist" $ExNoPath
     # Make sure that ${Conf['sleep']} is numeric
     val="${Conf['sleep']}"
     test "$(expr "$val" : '\([0-9]*\)')" = "$val" || ConfErr "required 'sleep' property must be numeric, not \"$val\""
@@ -319,20 +319,20 @@ ChkConf()
 
     # Check optional config parameters
     #   hostname: if param exists, it must have value $Host
-    if [ -v Conf['host'] -a -z "$NLocal" ]; then
+    if [[ -v Conf['host'] && -z "$NLocal" ]]; then
 	val="${Conf['host']}"
 	test "$Host" = "$val" || ConfErr "host \"$val\" does not match system's \"$Host\"" $ExNotHost
     fi
 
     #	shell: if param exists it must be known from 'command -v'
-    if [ -v Conf['shell'] -a -z "$NLocal" ]; then
+    if [[ -v Conf['shell'] && -z "$NLocal" ]]; then
 	val=$(command -v "${Conf['shell']}") && Shell="$val" || ConfErr "shell \"${Conf['shell']}\" is not valid" $ExNoPath
     fi
 
     #	debug: if param exists, it must have value 'true' or 'false'
     if [ -v Conf['debug'] ]; then
 	val="${Conf['debug']}"
-	test "$val" = 'true' -o "$val" = 'false' || ConfErr "debug parameter has value \"$val\", not 'true' or 'false'"
+	[[ "$val" =~ ^(true|false)$ ]] || ConfErr "debug parameter has value \"$val\", not 'true' or 'false'"
     fi
 
     # Check for required dicts
@@ -351,10 +351,10 @@ ChkConf()
 	done
 	# method has fixed values
 	val="${Conf["filetypes.$key.method"]}"
-	test "$val" = 'fileglob' -o "$val" = 'regexp' || ConfErr "filetypes.$key.method has invalid value \"$val\""
+	[[ "$val" =~ ^(fileglob|regexp)$ ]] || ConfErr "filetypes.$key.method has invalid value \"$val\""
 	# optional orderby has fixed values
 	val="${Conf["filetypes.$key.orderby"]}"
-	test "$val" = 'mtime' -o "$val" = 'alpha' -o "$val" = '' || ConfErr "filetypes.$key.orderby has invalid value \"$val\""
+	[[ "$val" =~ ^(mtime|alpha|)$ ]] || ConfErr "filetypes.$key.orderby has invalid value \"$val\""
     done
 
     # Check actions dict
@@ -365,7 +365,7 @@ ChkConf()
 	# check that optionnal chdir's directory exists
 	if [ -v Conf["actions.$key.chdir"] ]; then
 	    val="${Conf["actions.$key.chdir"]}"
-	    test -d "$val" -o "$val" = 'null' || ConfErr "actions.$key.chdir directory \"$val\" does not exist"
+	    [[ -d "$val" || "$val" = 'null' ]] || ConfErr "actions.$key.chdir directory \"$val\" does not exist"
 	fi
     done
 
@@ -377,12 +377,12 @@ ChkConf()
 	# check that optionnal chdir's directory exists
 	if [ -v Conf["ends.$key.chdir"] ]; then
 	    val="${Conf["ends.$key.chdir"]}"
-	    test -d "$val" -o "$val" = 'null' || ConfErr "ends.$key.chdir directory \"$val\" does not exist"
+	    [[ -d "$val" || "$val" = 'null' ]] || ConfErr "ends.$key.chdir directory \"$val\" does not exist"
 	fi
 	# optional stdin has fixed values
 	if [ -v Conf["ends.$key.stdin"] ]; then
 	    val="${Conf["ends.$key.stdin"]}"
-	    test "$val" = 'out' -o "$val" = 'err' -o "$val" = 'all' || ConfErr "ends.$key.stdin has invalid value \"$val\""
+	    [[ "$val" =~ ^(out|err|all)$ ]] || ConfErr "ends.$key.stdin has invalid value \"$val\""
 	fi
     done
 
@@ -403,7 +403,7 @@ ChkConf()
 	    # check args.facility
 	    test -v Conf["logs.$key.args.facility"] || ConfErr "logs.$key has no 'facility' property in 'args'"
 	    val="${Conf["logs.$key.args.facility"]}"
-	    test "$val" = 'user' -o "$val" = 'daemon' || ConfErr "logs.$key.facility has invalid value \"$val\""
+	    [[ "$val" =~ ^(user|daemon)$ ]] || ConfErr "logs.$key.facility has invalid value \"$val\""
 	    # check args.level
 	    test -v Conf["logs.$key.args.level"] || ConfErr "logs.$key has no 'level' property in 'args'"
 	    val="${Conf["logs.$key.args.level"]}"
@@ -437,7 +437,7 @@ ChkConf()
 	    test -v Conf["actions.$val.cmd"] || ConfErr "$step.action \"$val\" does not match any 'actions' member"
 	    if [ -v Conf["$step.hide"] ]; then
 		val="${Conf["$step.hide"]}"
-		test "$val" = 'true' -o "$val" = 'false' || ConfErr "$step.hide has value \"$val\", not 'true' or 'false'"
+		[[ "$val" =~ ^(true|false)$ ]] || ConfErr "$step.hide has value \"$val\", not 'true' or 'false'"
 	    fi
 
 	    # a step may have a list of ends
@@ -472,7 +472,7 @@ ChkConf()
     # Make sure our .path has its dir
     mkdir -p $1		# make our rundir if necessary
     path="$1/${Tag}_path"
-    if [ -e "$path" -o -L "$path" ]; then
+    if [[ -e "$path" || -L "$path" ]]; then
 	if [ -L "$path" ]; then	# $path is a symbolic link (orphan or not)
 	    link=$(readlink "$path")
 	    #echo "path='$path' link='$link' conf='${Conf['path']}'"
@@ -605,6 +605,7 @@ SigUsr2()
 #   We need a tag as our first argument
 #   so we can load and check our config
 #
+CfgDir='' AllCfg='' NLocal=''
 eval "CfgDir=\${${IndPfx}CFGDIR:-/etc/\$Prg.d}"		# Derive default cfgdir from $Prg
 eval "AllCfg=\${${IndPfx}CONFIG:-/etc/\$Prg.conf}"	# Derive default file from $Prg
 
@@ -669,8 +670,8 @@ case "$Cmd" in
     *)	Usage;;	# Reject unknown 2nd arg
 esac
 
-if test -z "$NoCache" -a -s "$Cache"; then
-    if [ "$SubCmd" = 'chk' -o "$SubCmd" = 'prt' ]; then
+if [[ -z "$NoCache" && -s "$Cache" ]]; then
+    if [[ "$SubCmd" =~ ^(chk|prt)$ ]]; then
 	FromCache='c'	# 'c' as sub-Commands
     elif [ "$(mTime "$Cache")" -gt "$(mTime "$Config")" ]; then
 	FromCache='t'	# 't' as newer-Time
@@ -955,7 +956,7 @@ do
 
 		    # Optional action's chdir
 		    ChDir=
-		    test -v Conf["$act.chdir"] -a "${Conf["$act.chdir"]}" != 'null' && ChDir=" cd ${Conf["$act.chdir"]};"
+		    [[ -v Conf["$act.chdir"] && "${Conf["$act.chdir"]}" != 'null' ]] && ChDir=" cd ${Conf["$act.chdir"]};"
 
 		    # Optional action's env
 		    for sfx in ${Conf["$act.env._keys"]}	# May not exist
@@ -995,24 +996,24 @@ do
 		    TmpAll=
 		    beg=$(date '+%s')
 		    # Optimize temp file usage in our .cmd call
-		    if [ -z "$StdIns" -o "$StdIns" = 'all' ]; then
+		    if [[ "$StdIns" =~ ^(|all)$ ]]; then
 			# Only 'all' (merge)
 			test "$StdIns" && TmpAll=$(mktemp $TmpDir/$Prg-XXXXXXXX.all) || TmpAll=/dev/null
 			LogDbg "          using $TmpAll"
 			$Shell -c "$ThisEnv;$ChDir ${Conf["$act.cmd"]}" >$TmpAll 2>&1
 			xc=$?
-		    elif [ "$StdIns" = 'out' -o "$StdIns" = 'err' -o "$StdIns" = 'out err' ]; then
+		    elif [[ "$StdIns" =~ ^(out|err|out err)$ ]]; then
 			# No 'all' (split)
-			grep out <<<"$StdIns" >/dev/null && TmpOut=$(mktemp $TmpDir/$Prg-XXXXXXXX.out) || TmpOut=/dev/null
-			grep err <<<"$StdIns" >/dev/null && TmpErr=$(mktemp $TmpDir/$Prg-XXXXXXXX.err) || TmpOut=/dev/null
+			[[ "$StdIns" =~ out ]] && TmpOut=$(mktemp $TmpDir/$Prg-XXXXXXXX.out) || TmpOut=/dev/null
+			[[ "$StdIns" =~ err ]] && TmpErr=$(mktemp $TmpDir/$Prg-XXXXXXXX.err) || TmpOut=/dev/null
 			LogDbg "          using $TmpOut and $TmpErr"
 			$Shell -c "$ThisEnv;$ChDir ${Conf["$act.cmd"]}" >$TmpOut 2>$TmpErr
 			xc=$?
 		    else
 			# Mix (combo): prepare Tmp files
 			TmpAll=$(mktemp $TmpDir/$Prg-XXXXXXXX.all)
-			grep out <<<"$StdIns" >/dev/null && TmpOut=$(mktemp $TmpDir/$Prg-XXXXXXXX.out)
-			grep err <<<"$StdIns" >/dev/null && TmpErr=$(mktemp $TmpDir/$Prg-XXXXXXXX.err)
+			[[ "$StdIns" =~ out ]] && TmpOut=$(mktemp $TmpDir/$Prg-XXXXXXXX.out)
+			[[ "$StdIns" =~ err ]] && TmpErr=$(mktemp $TmpDir/$Prg-XXXXXXXX.err)
 			# Different combo modes
 			if [ "$StdIns" = 'out all' ]; then
 			    LogDbg "          using $TmpOut and $TmpAll"
@@ -1046,7 +1047,7 @@ do
 
 			# Optional end's chdir
 			Chdir=
-			test -v Conf["$end.chdir"] -a "${Conf["$end.chdir"]}" != 'null' && ChDir=" cd ${Conf["$end.chdir"]};"
+			[[ -v Conf["$end.chdir"] && "${Conf["$end.chdir"]}" != 'null' ]] && ChDir=" cd ${Conf["$end.chdir"]};"
 			# Optional end's env
 			for sfx in ${Conf["$end.env._keys"]}	# May not exist
 			do
