Update start-limit/check-systemd-sources to be more generic

diff --git a/start-limit/check-systemd-sources b/start-limit/check-systemd-sources
--- a/start-limit/check-systemd-sources
+++ b/start-limit/check-systemd-sources
@@ -1,32 +1,56 @@
 #!/bin/sh
-
+#
+#	check-systemd-sources - Check that StartLimitInterval is still valid
+#
 Prg=$(basename $0)
 cd $(dirname $0)
-mkdir work || { echo "$Prg: directory 'work' already exists. Remove or rename it to proceed..." >&2; exit 1; }
-exec 2>$Prg.log
-get()
-{
-    wget --progress=dot:mega "$@"
+
+rel='systemd-releases'
+test -s "$rel" || { echo "$Prg: cannot find the '$rel' file" >&2; exit 1; }
+<"$rel" awk 'NF != 6 {exit 1}' || { 
+    echo "$Prg: file '$rel' should have 6 columns: sdVer sdRel 'deb' debVer sdUpd debRel" >&2
+    exit 2
 }
+
+mkdir work 2>/dev/null || {
+    echo "$Prg: directory 'work' already exists. Remove or rename it to proceed..." >&2
+    exit 1
+}
+
+path='/pool/main/s/systemd'
+main='http://ftp.debian.org/debian'
+arch='http://archive.debian.org/debian'
+elts='http://deb.freexian.com/extended-lts'
+
 cd work
-get http://ftp.debian.org/debian/pool/main/s/systemd/systemd_232.orig.tar.gz
-get http://deb.freexian.com/extended-lts/pool/main/s/systemd/systemd_232-25+deb9u15.debian.tar.xz
-get http://ftp.debian.org/debian/pool/main/s/systemd/systemd_241.orig.tar.gz
-get http://ftp.debian.org/debian/pool/main/s/systemd/systemd_241-7~deb10u8.debian.tar.xz
-get http://ftp.debian.org/debian/pool/main/s/systemd/systemd_247.3.orig.tar.gz
-get http://ftp.debian.org/debian/pool/main/s/systemd/systemd_247.3-7+deb11u1.debian.tar.xz
-get "http://ftp.debian.org/debian/pool/main/s/systemd" 
-mv systemd systemd.html
-tar xf systemd_232.orig.tar.gz
-cd systemd-232
-tar xf ../systemd_232-25+deb9u15.debian.tar.xz 
-cd ..
-tar xf systemd_241.orig.tar.gz
-cd systemd-241
-tar xf ../systemd_241-7~deb10u8.debian.tar.xz
-cd ..
-tar xf systemd_247.3.orig.tar.gz
-cd systemd-stable-247.3
-tar xf ../systemd_247.3-7+deb11u1.debian.tar.xz
-cd ..
-find systemd-* -type f -print0 | sort -z | xargs -0 grep '[^t]StartLimitInter' >grep.out
+
+get() { wget -q "$@"; }
+
+echo "Fetching systemd file-lists"
+get "$arch$path" -O arch.html
+get "$main$path" -O main.html
+get "$elts$path" -O elts.html
+
+echo "Fetching sources"
+while read -r sver srel deb dver upd drel; do
+    orig="systemd_$sver.orig.tar.gz"
+    eval "site=\$$(grep "$orig" *.html | sed -nr 's/^(....)\.html:.*$/\1/p' | sed -n 1p)"
+    get "$site$path/$orig"
+done <../$rel
+
+echo "Fetching Debian patches"
+while read -r sver srel deb dver upd drel; do
+    eval "$(grep -E "systemd_$sver-[0-9]+.*deb${dver}u[0-9]+.debian.tar.xz" *.html | sed -nr 's/^(....)\.html:.*href="([^"]+)".*$/site=$\1 orig=\2/p' | sort -tu -n -k2,2 | tail -1)"
+    get "$site$path/$orig"
+done <../$rel
+
+echo "Extracting sources & Debian patches"
+for v in $(awk -F'\t' '{print $1}' ../$rel)
+do
+    tar xf systemd_$v*.orig.tar.gz
+    cd systemd-*$v*
+    tar xf ../systemd_$v*.debian.tar.xz
+    cd ..
+done
+echo "Look for StartLimitInter"
+find systemd-* -type f -print0 | sort -z | xargs -0 grep '[^t]StartLimitInter' >../StartLimitInter
